### ISSUE TITLE
es6 proxies

### ISSUE THREAD

**Issue by pkieltyka** [BeTomorrow/micro-observables#6]
Hi there,

Just wondering on your thoughts for an es6 proxies version of this library? 

browser support is decent. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

**Comment by simontreny** [comment]
ES6 proxies is a powerful tool, but it adds "implicitness" in your code and I personally think it leads to code that is harder to understand and debug. If you are interested by this approach, you can have a look to [MobX](https://mobx.js.org) that is entirely built on proxies.
